#!/bin/bash
archi="amd64"
#archi="i386"

debian_version="buster"

dist_name="IXOS"

iso_name="IXOS-buster-amd64.iso"

#boot_default="ram"
boot_default=""
#boot_default="failsafe"

livework="./livework"


mirror="http://ftp.nl.debian.org/debian" # use by debootstrap
sources_list="deb $mirror ${debian_version} main" # if not empty, replace /etc/apt/sources.list by this content
