# CMake generated Testfile for 
# Source directory: /etc/calamares/src/modules
# Build directory: /etc/calamares/src/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(config-bootloader "/etc/calamares/test_conf" "/etc/calamares/src/modules/bootloader/bootloader.conf")
add_test(load-bootloader "/etc/calamares/loadmodule" "bootloader")
set_tests_properties(load-bootloader PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-contextualprocess "/etc/calamares/test_conf" "/etc/calamares/src/modules/contextualprocess/contextualprocess.conf")
add_test(config-displaymanager "/etc/calamares/test_conf" "/etc/calamares/src/modules/displaymanager/displaymanager.conf")
add_test(load-displaymanager "/etc/calamares/loadmodule" "displaymanager")
set_tests_properties(load-displaymanager PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-dracut "/etc/calamares/loadmodule" "dracut")
set_tests_properties(load-dracut PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-dummycpp "/etc/calamares/test_conf" "/etc/calamares/src/modules/dummycpp/dummycpp.conf")
add_test(config-dummypython "/etc/calamares/test_conf" "/etc/calamares/src/modules/dummypython/dummypython.conf")
add_test(load-dummypython "/etc/calamares/loadmodule" "dummypython")
set_tests_properties(load-dummypython PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-finished "/etc/calamares/test_conf" "/etc/calamares/src/modules/finished/finished.conf")
add_test(config-fsresizer "/etc/calamares/test_conf" "/etc/calamares/src/modules/fsresizer/fsresizer.conf")
add_test(config-fstab "/etc/calamares/test_conf" "/etc/calamares/src/modules/fstab/fstab.conf")
add_test(load-fstab "/etc/calamares/loadmodule" "fstab")
set_tests_properties(load-fstab PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-grubcfg "/etc/calamares/test_conf" "/etc/calamares/src/modules/grubcfg/grubcfg.conf")
add_test(load-grubcfg "/etc/calamares/loadmodule" "grubcfg")
set_tests_properties(load-grubcfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-grubcfg-1 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/grubcfg/tests/1.global" "grubcfg")
set_tests_properties(load-grubcfg-1 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-grubcfg-2 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/grubcfg/tests/2.global" "-j" "/etc/calamares/src/modules/grubcfg/tests/2.job" "grubcfg")
set_tests_properties(load-grubcfg-2 PROPERTIES  DEPENDS "make-grubcfg-dirs" WORKING_DIRECTORY "/etc/calamares")
add_test(make-grubcfg-dirs "/usr/bin/cmake" "-E" "make_directory" "/tmp/calamares/etc/default")
add_test(load-hwclock "/etc/calamares/loadmodule" "hwclock")
set_tests_properties(load-hwclock PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-initcpio "/etc/calamares/test_conf" "/etc/calamares/src/modules/initcpio/initcpio.conf")
add_test(load-initcpiocfg "/etc/calamares/loadmodule" "initcpiocfg")
set_tests_properties(load-initcpiocfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-initramfs "/etc/calamares/test_conf" "/etc/calamares/src/modules/initramfs/initramfs.conf")
add_test(load-initramfscfg "/etc/calamares/loadmodule" "initramfscfg")
set_tests_properties(load-initramfscfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-interactiveterminal "/etc/calamares/test_conf" "/etc/calamares/src/modules/interactiveterminal/interactiveterminal.conf")
add_test(config-keyboard "/etc/calamares/test_conf" "/etc/calamares/src/modules/keyboard/keyboard.conf")
add_test(config-keyboardq "/etc/calamares/test_conf" "/etc/calamares/src/modules/keyboardq/keyboardq.conf")
add_test(config-license "/etc/calamares/test_conf" "/etc/calamares/src/modules/license/license.conf")
add_test(config-locale "/etc/calamares/test_conf" "/etc/calamares/src/modules/locale/locale.conf")
add_test(load-localecfg "/etc/calamares/loadmodule" "localecfg")
set_tests_properties(load-localecfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-localeq "/etc/calamares/test_conf" "/etc/calamares/src/modules/localeq/localeq.conf")
add_test(config-luksopenswaphookcfg "/etc/calamares/test_conf" "/etc/calamares/src/modules/luksopenswaphookcfg/luksopenswaphookcfg.conf")
add_test(load-luksopenswaphookcfg "/etc/calamares/loadmodule" "luksopenswaphookcfg")
set_tests_properties(load-luksopenswaphookcfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-machineid "/etc/calamares/test_conf" "/etc/calamares/src/modules/machineid/machineid.conf")
add_test(config-mount "/etc/calamares/test_conf" "/etc/calamares/src/modules/mount/mount.conf")
add_test(load-mount "/etc/calamares/loadmodule" "mount")
set_tests_properties(load-mount PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-netinstall "/etc/calamares/test_conf" "/etc/calamares/src/modules/netinstall/netinstall.conf")
add_test(load-networkcfg "/etc/calamares/loadmodule" "networkcfg")
set_tests_properties(load-networkcfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-notesqml "/etc/calamares/test_conf" "/etc/calamares/src/modules/notesqml/notesqml.conf")
add_test(config-oemid "/etc/calamares/test_conf" "/etc/calamares/src/modules/oemid/oemid.conf")
add_test(config-openrcdmcryptcfg "/etc/calamares/test_conf" "/etc/calamares/src/modules/openrcdmcryptcfg/openrcdmcryptcfg.conf")
add_test(load-openrcdmcryptcfg "/etc/calamares/loadmodule" "openrcdmcryptcfg")
set_tests_properties(load-openrcdmcryptcfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-packagechooser "/etc/calamares/test_conf" "/etc/calamares/src/modules/packagechooser/packagechooser.conf")
add_test(config-packages "/etc/calamares/test_conf" "/etc/calamares/src/modules/packages/packages.conf")
add_test(load-packages "/etc/calamares/loadmodule" "packages")
set_tests_properties(load-packages PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-partition "/etc/calamares/test_conf" "/etc/calamares/src/modules/partition/partition.conf")
add_test(config-plymouthcfg "/etc/calamares/test_conf" "/etc/calamares/src/modules/plymouthcfg/plymouthcfg.conf")
add_test(load-plymouthcfg "/etc/calamares/loadmodule" "plymouthcfg")
set_tests_properties(load-plymouthcfg PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-preservefiles "/etc/calamares/test_conf" "/etc/calamares/src/modules/preservefiles/preservefiles.conf")
add_test(config-rawfs "/etc/calamares/test_conf" "/etc/calamares/src/modules/rawfs/rawfs.conf")
add_test(load-rawfs "/etc/calamares/loadmodule" "rawfs")
set_tests_properties(load-rawfs PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-rawfs-1 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/rawfs/tests/1.global" "-j" "/etc/calamares/src/modules/rawfs/tests/1.job" "rawfs")
set_tests_properties(load-rawfs-1 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-removeuser "/etc/calamares/test_conf" "/etc/calamares/src/modules/removeuser/removeuser.conf")
add_test(config-services-openrc "/etc/calamares/test_conf" "/etc/calamares/src/modules/services-openrc/services-openrc.conf")
add_test(load-services-openrc "/etc/calamares/loadmodule" "services-openrc")
set_tests_properties(load-services-openrc PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-services-systemd "/etc/calamares/test_conf" "/etc/calamares/src/modules/services-systemd/services-systemd.conf")
add_test(load-services-systemd "/etc/calamares/loadmodule" "services-systemd")
set_tests_properties(load-services-systemd PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-shellprocess "/etc/calamares/test_conf" "/etc/calamares/src/modules/shellprocess/shellprocess.conf")
add_test(config-tracking "/etc/calamares/test_conf" "/etc/calamares/src/modules/tracking/tracking.conf")
add_test(config-umount "/etc/calamares/test_conf" "/etc/calamares/src/modules/umount/umount.conf")
add_test(load-umount "/etc/calamares/loadmodule" "umount")
set_tests_properties(load-umount PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-unpackfs "/etc/calamares/test_conf" "/etc/calamares/src/modules/unpackfs/unpackfs.conf")
add_test(load-unpackfs "/etc/calamares/loadmodule" "unpackfs")
set_tests_properties(load-unpackfs PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-1 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/1.global" "unpackfs")
set_tests_properties(load-unpackfs-1 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-2 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/2.global" "unpackfs")
set_tests_properties(load-unpackfs-2 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-3 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/3.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/3.job" "unpackfs")
set_tests_properties(load-unpackfs-3 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-4 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/4.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/4.job" "unpackfs")
set_tests_properties(load-unpackfs-4 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-5 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/5.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/5.job" "unpackfs")
set_tests_properties(load-unpackfs-5 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-6 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/6.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/6.job" "unpackfs")
set_tests_properties(load-unpackfs-6 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-7 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/7.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/7.job" "unpackfs")
set_tests_properties(load-unpackfs-7 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-8 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/8.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/8.job" "unpackfs")
set_tests_properties(load-unpackfs-8 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(load-unpackfs-9 "/etc/calamares/loadmodule" "-g" "/etc/calamares/src/modules/unpackfs/tests/9.global" "-j" "/etc/calamares/src/modules/unpackfs/tests/9.job" "unpackfs")
set_tests_properties(load-unpackfs-9 PROPERTIES  WORKING_DIRECTORY "/etc/calamares")
add_test(config-users "/etc/calamares/test_conf" "/etc/calamares/src/modules/users/users.conf")
add_test(config-webview "/etc/calamares/test_conf" "/etc/calamares/src/modules/webview/owncloud.conf")
add_test(config-webview-1 "/etc/calamares/test_conf" "/etc/calamares/src/modules/webview/webview.conf")
add_test(config-welcome "/etc/calamares/test_conf" "/etc/calamares/src/modules/welcome/welcome.conf")
add_test(config-welcomeq "/etc/calamares/test_conf" "/etc/calamares/src/modules/welcomeq/welcomeq.conf")
subdirs("contextualprocess")
subdirs("dracutlukscfg")
subdirs("dummycpp")
subdirs("finished")
subdirs("fsresizer")
subdirs("hostinfo")
subdirs("initcpio")
subdirs("initramfs")
subdirs("interactiveterminal")
subdirs("keyboard")
subdirs("keyboardq")
subdirs("license")
subdirs("locale")
subdirs("localeq")
subdirs("luksbootkeyfile")
subdirs("machineid")
subdirs("netinstall")
subdirs("notesqml")
subdirs("oemid")
subdirs("packagechooser")
subdirs("partition")
subdirs("plasmalnf")
subdirs("preservefiles")
subdirs("removeuser")
subdirs("shellprocess")
subdirs("summary")
subdirs("tracking")
subdirs("users")
subdirs("webview")
subdirs("welcome")
subdirs("welcomeq")
